baseURL: "https://prasadmahamulkar.com/"
title: Prasad Mahamulkar
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Prasad Mahamulkar
  description: "Become a data expert faster, easier, and more enjoyable with mlquest.
    Learn about data science, machine learning, and more."
  keywords: [Blog, Machine Learning, Data Science]
  author: Prasad Mahamulkar
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false


  label:
    text: "🤖Prasad Mahamulkar"
    icon: 
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Data Scientist and ML engineer"
    subtitle: "Hello! My name is Prasad Mahamulkar.\n\n\n I hold a M.Sc. in Data Science from Cardiff University. 
    On this site, I publish technical articles, covering topics such as Data Science, Machine Learning, and MLOps."
    imageUrl: "images/photo.png"
    imageWidth: 150
    imageHeight: 150
    imageTitle: "prasad logo"
    buttons:
      - name: Read Now
        url: blog
      - name: Videos 
        url: https://www.youtube.com/channel/UCzjannpvFjl-QTWFPyFpKaQ


  socialIcons:
    - name: github
      url: "https://github.com/Dataflaresite?tab=repositories"
    - name: youtube
      url: "https://www.youtube.com/channel/UCzjannpvFjl-QTWFPyFpKaQ"
    - name: "email"
      url: "mailto:hello@thedataflare.com"
    - name: linkedin
      url: "https://www.linkedin.com/company/dataflare-tech/"
    - name: buymeacoffee
      url: "https://www.buymeacoffee.com/dataprofessor"
    - name: newsletter
      url: "https://www.buymeacoffee.com/dataprofessor"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page


  editPost:
#    URL: "https://github.com/chanin-www/content"
#    Text: "Suggest Changes" # edit text
    URL: ""
    Text: "" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 20 
    - identifier: blog
      name: Blogs
      url: /blog/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: search
      name: Search
      url: /search
      weight: 40

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
